### ISSUE TITLE
Enquiry Related Documentation of Running The Project

### ISSUE THREAD

**Issue by tldrjumps** [rundexter/instapaper-add-new-bookmark#1]
Is this project supported on http://docs.rundexter.com/.
Is there anyway to setup the node,js backend to support incoming message on rundexter.com to add new bookmark?

**Comment by ilkovich** [comment]
Unfortunately this module is not directly supported on the current iteration of rundexter.com. You could build something similar using our [HTTP Requests](http://docs.rundexter.com/writing/advanced/http-requests/#toc)
